PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
      ?derivedUnit
      ?factorUnit
      ?exponent
      ?scaleFactor
WHERE
{
    ?derivedUnit qudt:hasFactorUnit ?endFactor .
    ?endFactor
        qudt:hasUnit ?factorUnit ;
        qudt:exponent ?exponent .
    OPTIONAL {
        ?derivedUnit qudt:factorUnitScalar ?scaleFactor
    }
}
ORDER BY ?derivedUnit ?factorUnit



