PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>


SELECT DISTINCT * where
{
    ?quantityKind a qudt:QuantityKind;
        {
            optional {
                ?quantityKind rdfs:label ?label .
            }
            optional {
                ?quantityKind qudt:deprecated ?deprecated
            }
            optional {
                ?quantityKind qudt:applicableUnit ?applicableUnit
            }
            optional {
                ?quantityKind qudt:hasDimensionVector ?dimensionVector
            }
            optional {
                ?quantityKind qudt:qkdvNumerator ?qkdvNumerator
            }
            optional {
                ?quantityKind qudt:qkdvDenominator ?qkdvDenominator
            }
            optional {
               ?quantityKind qudt:symbol ?symbol
            }
            optional {
               ?quantityKind skos:broader ?broaderQuantityKind
            }
            OPTIONAL {
               ?quantityKind dcterms:description ?description ;
            }
        } UNION {
            optional {
                ?quantityKind qudt:exactMatch ?exactMatch
                optional {
                    ?exactMatch qudt:applicableUnit ?applicableUnit
                }
                optional {
                    ?quantityKind qudt:deprecated ?deprecated
                }
                optional {
                    ?exactMatch qudt:hasDimensionVector ?dimensionVector
                }
                optional {
                    ?exactMatch qudt:qkdvNumerator ?qkdvNumerator
                }
                optional {
                    ?exactMatch qudt:qkdvDenominator ?qkdvDenominator
                }
                optional {
                   ?exactMatch qudt:symbol ?symbol
                }
                optional {
                   ?exactMatch skos:broader ?broaderQuantityKind
                }
                OPTIONAL {
                   ?quantityKind dcterms:description ?description ;
                }
            }
    }
} order by ?quantityKind
