PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * where
{
    {
        ?unit a qudt:Unit;
        rdfs:label ?label .
    } UNION {
        ?unit a qudt:CurrencyUnit;
        rdfs:label ?label .
    }
    optional {
        ?unit qudt:exactMatch ?exactMatch
    }
    optional {
       ?unit qudt:hasQuantityKind ?quantityKind
    }
    optional {
       ?unit qudt:conversionMultiplier ?conversionMultiplier
    }
    optional {
        ?unit qudt:conversionOffset ?conversionOffset
    }
    optional {
       ?unit qudt:symbol ?symbol
    }
    optional {
       ?unit qudt:ucumCode ?ucumCode
    }
    optional {
        ?unit qudt:prefix ?prefix
    }
    optional {
        ?unit qudt:isScalingOf ?scalingOf
    }
    optional {
        ?unit qudt:hasDimensionVector ?dimensionVector
    }
    optional {
        ?unit qudt:currencyCode ?currencyCode
    }
    optional {
        ?unit qudt:currencyNumber ?currencyNumber
    }
    optional {
        ?unit qudt:applicableSystem|qudt:systemOfUnit|qudt:baseUnitOfSystem|qudt:derivedCoherentUnitOfSystem|qudt:derivedNonCoherentUnitOfSystem|qudt:derivedUnitOfSystem|qudt:coherentUnitOfSystem|qudt:definedUnitOfSystem|qudt:allowedUnitOfSystem ?systemOfUnits
    }
} order by ?unit
