#
# TODO: remove after pending PR has been merged
#
PREFIX qudt: <http://qudt.org/schema/qudt/>
DELETE { ?u qudt:conversionMultiplier ?m }
WHERE { ?u qudt:conversionMultiplier ?m .
VALUES  ?u {
<http://qudt.org/vocab/unit/A-PER-DEG_C>
<http://qudt.org/vocab/unit/ANGSTROM3>
<http://qudt.org/vocab/unit/A_Ab-CentiM2>
<http://qudt.org/vocab/unit/BAR-M3-PER-SEC>
<http://qudt.org/vocab/unit/BTU_IT-PER-HR-FT2-DEG_R>
<http://qudt.org/vocab/unit/BTU_IT-PER-SEC-FT-DEG_R>
<http://qudt.org/vocab/unit/BTU_IT-PER-SEC-FT2-DEG_R>
<http://qudt.org/vocab/unit/BTU_TH-PER-LB-DEG_F>
<http://qudt.org/vocab/unit/DEG_F-HR-FT2-PER-BTU_IT>
<http://qudt.org/vocab/unit/DEG_F-HR-FT2-PER-BTU_TH>
<http://qudt.org/vocab/unit/FT-LB_F-PER-HR>
<http://qudt.org/vocab/unit/GigaJ-PER-HR>
<http://qudt.org/vocab/unit/HART-PER-SEC>
<http://qudt.org/vocab/unit/J-PER-HR>
<http://qudt.org/vocab/unit/K-PER-HR>
<http://qudt.org/vocab/unit/KAT-PER-L>
<http://qudt.org/vocab/unit/KAT-PER-MicroL>
<http://qudt.org/vocab/unit/KiloA-HR>
<http://qudt.org/vocab/unit/KiloBTU_IT>
<http://qudt.org/vocab/unit/KiloBYTE-PER-SEC>
<http://qudt.org/vocab/unit/KiloCAL-PER-CentiM2-MIN>
<http://qudt.org/vocab/unit/KiloCAL-PER-CentiM2-SEC>
<http://qudt.org/vocab/unit/KiloCAL-PER-CentiM2>
<http://qudt.org/vocab/unit/KiloGM-PER-CentiM3>
<http://qudt.org/vocab/unit/KiloGM_F-PER-MilliM2>
<http://qudt.org/vocab/unit/KiloL-PER-HR>
<http://qudt.org/vocab/unit/KiloLB_F-FT-PER-A>
<http://qudt.org/vocab/unit/KiloMOL-PER-MIN>
<http://qudt.org/vocab/unit/KiloN-M-PER-DEG-M>
<http://qudt.org/vocab/unit/KiloPA-PER-MilliM>
<http://qudt.org/vocab/unit/KiloR>
<http://qudt.org/vocab/unit/KiloYR>
<http://qudt.org/vocab/unit/LA>
<http://qudt.org/vocab/unit/LB-PER-GAL_US>
<http://qudt.org/vocab/unit/MOL-PER-TONNE>
<http://qudt.org/vocab/unit/MegaJ-PER-HR>
<http://qudt.org/vocab/unit/MegaLB_F>
<http://qudt.org/vocab/unit/MicroGM-PER-CentiM2>
<http://qudt.org/vocab/unit/MicroGM-PER-DeciL>
<http://qudt.org/vocab/unit/MicroM-PER-MilliL>
<http://qudt.org/vocab/unit/MicroMOL-PER-GM-SEC>
<http://qudt.org/vocab/unit/MilliGAL-PER-MO>
<http://qudt.org/vocab/unit/MilliGM-PER-MilliL>
<http://qudt.org/vocab/unit/MilliM-PER-YR>
<http://qudt.org/vocab/unit/MilliR>
<http://qudt.org/vocab/unit/MilliRAD_R-PER-HR>
<http://qudt.org/vocab/unit/MilliR_man>
<http://qudt.org/vocab/unit/N-M-PER-DEG-M>
<http://qudt.org/vocab/unit/NUM-PER-CentiM-KiloYR>
<http://qudt.org/vocab/unit/NUM-PER-HA>
<http://qudt.org/vocab/unit/OZ-IN>
<http://qudt.org/vocab/unit/OZ-PER-GAL_US>
<http://qudt.org/vocab/unit/OZ_F-IN>
<http://qudt.org/vocab/unit/OZ_VOL_UK-PER-DAY>
<http://qudt.org/vocab/unit/OZ_VOL_UK-PER-HR>
<http://qudt.org/vocab/unit/OZ_VOL_UK-PER-MIN>
<http://qudt.org/vocab/unit/PER-ANGSTROM>
<http://qudt.org/vocab/unit/PER-HR>
<http://qudt.org/vocab/unit/PER-KiloV-A-HR>
<http://qudt.org/vocab/unit/PER-MIN>
<http://qudt.org/vocab/unit/PERCENT-PER-DAY>
<http://qudt.org/vocab/unit/PERCENT-PER-HR>
<http://qudt.org/vocab/unit/PERCENT-PER-M>
<http://qudt.org/vocab/unit/PERCENT-PER-WK>
<http://qudt.org/vocab/unit/R>
<http://qudt.org/vocab/unit/RAD-PER-HR>
<http://qudt.org/vocab/unit/RAD-PER-MIN>
<http://qudt.org/vocab/unit/SHANNON-PER-SEC>
}}
