PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX prefix: <http://qudt.org/vocab/prefix/>
PREFIX kind: <http://qudt.org/vocab/quantitykind/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {
    ?scaledUnit qudt:isScalingOf ?baseUnit .
}
where
{
    ?scaledUnit
        a qudt:Unit ;
        qudt:isScalingOf ?baseUnit .
    ?baseUnit a qudt:Unit .
    OPTIONAL {
        ?scaledUnit qudt:convertsTo ?convertsToUnit .
        ?convertsToUnit a qudt:Unit.
    }
    FILTER (?baseUnit = unit:KiloGM)
}



