PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX quantitykind: <http://qudt.org/vocab/quantitykind/>

DELETE {
    ?s rdfs:label ?label .
} WHERE {
    ?s rdfs:label ?label .
    FILTER( ! (LANG(?label) IN ("en","en-US")))
    FILTER EXISTS {
        ?s rdfs:label ?keep
        FILTER( LANG(?keep) IN ("en","en-US"))
    }
}